### ISSUE TITLE
Set up

### ISSUE THREAD

**Issue by GregStephen** [nss-evening-cohort-9/foundations-group-project-adios-pantalones#1]
# User Story
As a developer, I need all of the things, to do the other things.

# AC
**WHEN** I open the page
**THEN** it should be light blue, say Hi, and should console log "Suh dude"
**AND** it should have a bootstrap button

# Development
* Create index.html, main.js, main.css
* Create assets folder
* Create html boilerplate
* Link main.js, main.css, and bootstrap to index.html
* Change background color to blue
* Console.log("Suh dude")
* Add bootstrap button to html

**Comment by GregStephen** [comment]
Bootstrap setup : https://getbootstrap.com/docs/4.3/getting-started/introduction/

button (https://getbootstrap.com/docs/4.3/components/buttons/): 
``` html
<button type="button" class="btn btn-primary">Primary</button>
```

**Comment by zoeames** [comment]
👍
