### ISSUE TITLE
Comment builder

### ISSUE THREAD

**Issue by GregStephen** [nss-evening-cohort-9/foundations-group-project-adios-pantalones#10]
# User Story
As a user, when I add a comment, I want it to display as a media object.

# AC
**WHEN** I click the comment button and submit a name and a comment
**THEN** the name, and comment should show up as a media object
**AND** the image should be a stock beer photo
**AND** the name should be the media Heading
**AND** the comment should be in the body

# Development
* Make a `comments` array - empty on page load
* `addComment` function should make an object with 2 key/value pairs. key `name` with the value coming from the name input, and key `comment` with the value coming from the comment input.
Push that object into the `comments` array. Call `commentBuilder` function and pass the array of comments.
* Add a `commentBuilder` function which has 2 inputs - `arrayOfComments`, `divID`
* `commentBuilder` function should loop `arrayOfComments` and build up a domString of bootstrap media objects. The comments should go into a <p> tag with a class = `commentBody`. It should then pass the domString  and `comment-container` to `printToDom` function

**Comment by GregStephen** [comment]
Media objects - https://getbootstrap.com/docs/4.3/components/media-object/

https://www.w3schools.com/bootstrap/bootstrap_media_objects.asp

example - 
``` html
<div class="media">
  <img src="..." class="mr-3" alt="...">
  <div class="media-body">
    <h5 class="mt-0">Media heading</h5>
    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
  </div>
</div>
```

**Comment by zoeames** [comment]
👍

**Comment by wchipchase** [comment]
https://app.moqups.com/D3s3U7o2FC/edit/page/ae1848f1d

**Comment by wchipchase** [comment]
![image](https://user-images.githubusercontent.com/15699736/55278303-8a681000-52d8-11e9-8f9b-5f559ac34450.png)
