### ISSUE TITLE
Create beer cards

### ISSUE THREAD

**Issue by GregStephen** [nss-evening-cohort-9/foundations-group-project-adios-pantalones#13]
# User Story
As a user, when I navigate to the Brews page, I should see cards of beer information, 3 across.

# AC
**WHEN** I load the Brews page
**THEN** beer cards should load on the page
**AND** the card should have the name of the beer above
**AND** the card should have the image of the beer below that
**AND** the card should have the type of beer, ABV, IBU, and a few Tasting notes below that

# Development
* Create a brews.html page
* Link it to main.css, main.js, bootstrap and FontAwesome
* Make a `brews` array that consists of objects with 6 key/values : name, image, type, abv, ibu, and tastingNotes. tastingNotes should be an array.
* Add a brewCardBuilder function which has 1 input - `arrayOfBrews`
* `brewCardBuilder` should loop over `arrayOfBrews` and build up a domstring of bootstrap cards(add class `col-3`). It should then pass the string to `printToDom` function.

**Comment by GregStephen** [comment]
Accessing nested information - https://stackoverflow.com/questions/11922383/access-process-nested-objects-arrays-or-json

**Comment by zoeames** [comment]
how are the tasting notes going to be displayed?  How does that fit into your brewCardBuilder function?

**Comment by GregStephen** [comment]
The tasting notes are going to be displayed at the bottom of the card in a list format i.e. : 
"Tasting Notes: Malty Sweet Heavy"
We would have to have a for each loop in the for loop just for the `arrayOfBrews.tastingNotes` that spat out each value into the domstring element. Like so : 
``` js
const cardBuilder = () => {
    let domString = "";

    array.forEach((beer) => {
    domString += `<div class="beerCard col-4">`;
    domString +=    `<h1 class="beerName">${beer.name}</h1>`;
    domString +=    `<div class="beerDescription">`;
    domString +=        `<img class="beerImage" src=${beer.imageUrl}>`;
    domString +=        `<p class="beerType">${beer.type}</p>`;
    domString +=        `<p> Tasting Notes: `;
    beer.tastingNotes.forEach((type) => {
    domString +=        `${type} `;
    })
    domString +=        `</p>`;
    domString +=    `</div>`;
    domString += `</div>`;
    })
    
    printToDom("sampleDiv", domString);
};```

**Comment by wchipchase** [comment]
https://app.moqups.com/D3s3U7o2FC/edit/page/afbfcb7a4

**Comment by zoeames** [comment]
👍

**Comment by wchipchase** [comment]
![image](https://user-images.githubusercontent.com/15699736/55762926-936c8600-5a2a-11e9-9a7d-29db6d032c9e.png)
