### ISSUE TITLE
Create beer filter

### ISSUE THREAD

**Issue by GregStephen** [nss-evening-cohort-9/foundations-group-project-adios-pantalones#14]
# User Story
As a user, when I press the filter button, a list of types appear with checkboxes next to them. When I select the type or types of beer I want to filter and then press the submit button, the cards should only show the beers of the type or types I selected.

# AC
**WHEN** the filter button is pressed
**THEN** a form of checkboxes appears with types of beer and a submit button
**AND** the filter button disappears
**WHEN** the submit button is pressed the form disappears
**THEN** the filter button appears
**AND** only the beer cards that match the selected types are shown

# Development
* Add a filter button with id = `filterBtn`, add an eventlistener that calls a function called `showFilterForm`
* Add a form with id=`filterForm` with a list of checkboxes and types of beer and a button with the `submitBtn` add an eventlistener that calls a function called `filterCards`- hidden on page load
* Make a `showFilterForm` function that changes the `filterForm` to display: `block`
* Make a `filterCards` function that selects the id of all of the selected checkboxes using (.map and .get) and assigns it to a variable `typeChoices`. if `typeChoices` = 0 it just display all the cards and if not then loop through the values in `typeChoices` and if those values match the type value in the brews array then show those cards.

**Comment by GregStephen** [comment]
map - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map

get - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/get

jquery way to convert to javascript - 
```html
$("input:checkbox:checked").map(function(){
    return $(this).attr('id');
  }).get();
```

**Comment by zoeames** [comment]
you are not allowed to use jquery at this point.  what are you trying to do with the above code?

**Comment by wchipchase** [comment]
https://app.moqups.com/D3s3U7o2FC/edit/page/afbfcb7a4

**Comment by GregStephen** [comment]
So this was a code snippet from something I worked on. Just copied it in as a reference but forgot to change what I wanted to put in here. 

We need to loop through `typeChoices` and check to see if typeChoices[i].checked==true, then assign those choices to an empty array `choicesPicked` then add and if statement in our `brewCardBuilder` function that checks to see if `choicesPicked.length` === 0 it cycles through all of them and then if `choicesPicked` includes `brews.type` then it only loops through those and  prints those to dom

**Comment by wchipchase** [comment]
![image](https://user-images.githubusercontent.com/15699736/55278287-470da180-52d8-11e9-8ed3-d85909f23a00.png)

**Comment by zoeames** [comment]
ok cool. just make sure the vanilla JS version makes it in

**Comment by zoeames** [comment]
👍
