### ISSUE TITLE
Age Check

### ISSUE THREAD

**Issue by GregStephen** [nss-evening-cohort-9/foundations-group-project-adios-pantalones#15]
# User Story
As a user, when the page first loads a window will appear asking if I am over 21 or not. Pressing yes will take me to the homepage, pressing no will redirect me to a children’s site. 

# AC
**WHEN** the page loads
**THEN** a modal will appear
**AND** it will ask if the use is over 21
**WHEN** the user clicks yes
**THEN** the homepage will load
**WHEN** the user clicks no
**THEN** the user will be directed to random children’s site 

# Development 
* Add a `createModal` Function that runs `randomNumber` with passing in `max` as `(kidSites.length)` and assigns it to a variable `randomNum`. Then it builds a DomString making a modal with the href for the `No` button being `kidSites[randomNum]`. Then pass `printToDom`
* Add array `kidSites` with as many kid website domains as wanted
* Create `randomNumber` function -1 input - `max` that returns a random number between 0 and `max`

**Comment by zoeames** [comment]
👍

**Comment by wchipchase** [comment]
https://app.moqups.com/D3s3U7o2FC/edit/page/aa9df7b72
