### ISSUE TITLE
Anonymous Comment

### ISSUE THREAD

**Issue by GregStephen** [nss-evening-cohort-9/foundations-group-project-adios-pantalones#18]
# User Story
As a user, if I don't want to put my name in my comment, I can leave it blank and it will post as "Anonymous Beer Lover"

# AC
**WHEN** the name field is left blank
**AND** the comment button is pressed
**THEN** the media object is created with "Anonymous Beer Lover" as the name

# Development
* Add an if else statement in the `commentBuilder` that checks to see if the `nameInput` value is empty. If it is then replace the value with "Anonymous Beer Lover"

**Comment by zoeames** [comment]
👍

**Comment by wchipchase** [comment]
https://app.moqups.com/D3s3U7o2FC/edit/page/ae1848f1d

**Comment by wchipchase** [comment]
![image](https://user-images.githubusercontent.com/15699736/55278305-8dfb9700-52d8-11e9-91de-8da46e7f13bd.png)
