### ISSUE TITLE
Create Navbar

### ISSUE THREAD

**Issue by GregStephen** [nss-evening-cohort-9/foundations-group-project-adios-pantalones#2]
# User Story
As a user, when I look at any of the pages, I will see a navigation bar on the top with the logo of the company on the left, three social media icons next to that, and three links to the About, Brews, and Brewmasters pages on the right.

# AC
**GIVEN** I am a user
**WHEN** I want to navigate and I click the left logo
**THEN** I will go to the home page
**WHEN** I click the social media icons
**THEN**  I will be redirected to the appropriate social media site
**WHEN** I click the About link, Brews link, or the Brewmaster link
**THEN** I will be redirected to the appropriate page

# Development
* Pull in sample navbar
* Add logo to the assets folder
* Link to logo image
* Give the logo a class ="navbar-brand" 
* Link to fontawesome
* Create three social media links from Font Awesome: Facebook, Instagram and Twitter
* Create page links for About, Brews, Brewmasters with appropriate hrefs
* Make the navbar sticky icky on that top top
* Add to every html and change hrefs where necessary

**Comment by GregStephen** [comment]
Navbar (https://getbootstrap.com/docs/4.3/components/navbar/) 

``` html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
  </div>
</nav>
```

navbar -brand 
``` html
<!-- Just an image -->
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="#">
    <img src="/docs/4.3/assets/brand/bootstrap-solid.svg" width="30" height="30" alt="">
  </a>
</nav>
```

**Comment by GregStephen** [comment]
font-awesome : https://fontawesome.com/start

**Comment by zoeames** [comment]
👍

**Comment by zoeames** [comment]
its kinda overkill to have social media links in the navbar and footer.  generally you will see them just in the footer

**Comment by GregStephen** [comment]
Yeah that was a debate. We looked at 5 different beer sites and they all
had both so that’s what we went with. Especially with the sticky navbar it
seemed a bit excessive. We will discuss it again tomorrow.

**Comment by wchipchase** [comment]
https://app.moqups.com/D3s3U7o2FC/edit/page/aa9df7b72

**Comment by wchipchase** [comment]
![image](https://user-images.githubusercontent.com/15699736/55278274-01e96f80-52d8-11e9-9db8-cc5ed5fb3874.png)
