### ISSUE TITLE
Create Carousel

### ISSUE THREAD

**Issue by GregStephen** [nss-evening-cohort-9/foundations-group-project-adios-pantalones#3]
# User Story
As a user, when I load the home page, there will be a carousel of 3 images that cycle through behind some static text

# AC
**WHEN** I am on the page
**THEN** the carousel cycles through images
**ALSO** when I click the left or right arrows on the carousel
**THEN** it cycles left or right
**AND** there is text about the brewery over all of these images

# Development
* Import basic carousel code from comments
* Add 3 images to Assets folder
* Change div id from "carouselExampleIndicators" to `apbCarousel`
* Link images to individual src on the carousel div
* Add text to show in front of the carousel - see commented note for howto

**Comment by GregStephen** [comment]
Carousel - https://getbootstrap.com/docs/4.3/components/carousel/

``` html
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
```

Adding text over carousel - https://stackoverflow.com/questions/29734492/adding-text-over-an-image-in-bootstrap-carousel

**Comment by zoeames** [comment]
👍 +1

**Comment by wchipchase** [comment]
https://app.moqups.com/D3s3U7o2FC/edit/page/aa9df7b72

**Comment by wchipchase** [comment]
![image](https://user-images.githubusercontent.com/15699736/55278272-fc8c2500-52d7-11e9-8e42-41c1e17dac62.png)
