### ISSUE TITLE
Create Footer

### ISSUE THREAD

**Issue by GregStephen** [nss-evening-cohort-9/foundations-group-project-adios-pantalones#4]
# User Story
As a user, when I scroll to the bottom of any of this magnificent brewery's pages, I will find a footer containing the brewery's address, their email and contact number, link to the pages and the social media icons

# AC
**WHEN** I navigate to the bottom of any of the pages
**THEN** I will see a footer containing the brewery's address, their email and contact number, link to the pages and the social media icons
**WHEN** I click the address it will pop up a navigation app 
**WHEN** I click the phone number it will allow me to call them
**WHEN** I click the email it will pop open my default email app
**WHEN** I click all the other links and icons
**THEN** I will be redirected to the appropriate page

# Development
* Create a footer div
* Make sure fontawesome is linked to HTML
* Add font awesome icons for Facebook, Instagram and Twitter
* Add links to other pages with appropriate hrefs
* Add contact information
* Add to every html page with changed links when appropriate

**Comment by GregStephen** [comment]
font awesome - https://fontawesome.com/start

**Comment by GregStephen** [comment]
Put everything in an address div - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/address

For the map - https://www.techrepublic.com/article/link-the-business-address-on-your-website-to-a-google-map/

For the phone - https://stackoverflow.com/questions/1608548/how-to-trigger-a-phone-call-when-clicking-a-link-in-a-web-page-on-mobile-phone

For the email - <a href="mailto:nowhere@mozilla.org">Send email to nowhere</a>

**Comment by zoeames** [comment]
👍

**Comment by wchipchase** [comment]
https://app.moqups.com/D3s3U7o2FC/edit/page/aa9df7b72

**Comment by wchipchase** [comment]
![image](https://user-images.githubusercontent.com/15699736/55278270-f0a06300-52d7-11e9-86e9-170eb520c76a.png)
