### ISSUE TITLE
Create Card Links

### ISSUE THREAD

**Issue by GregStephen** [nss-evening-cohort-9/foundations-group-project-adios-pantalones#5]
# User Story
As a user, when I look at the page, below the carousel I would see three cards with images, a title  above and a description below that link to the About me, Brews, and Brewmaster pages

# AC
**WHEN** the page loads
**THEN** there should be three bootstrap cards below the carousel
**AND** the cards should have an image with a title and a small description
**WHEN** I click any of the cards images
**THEN** it links to the appropriate page
**AND** the cards should be in a row of 3

# Development
* Add images to assets folder
* Create an array `linkCards` of  3 objects with keys - img, title, description
* Create a div with id="linkCardsDiv"
* Create a `createLinkCard` function -2 inputs- `arrayOfLinkCards`,` divId` - function should loop over the `arrayOfLinkCards`  and builds a domString of bootstrap card (add class = `col-4`) and then passes the string and the `linkCardsDiv` to `printToDom` function

**Comment by zoeames** [comment]
👍

**Comment by wchipchase** [comment]
https://app.moqups.com/D3s3U7o2FC/edit/page/aa9df7b72

**Comment by wchipchase** [comment]
![image](https://user-images.githubusercontent.com/15699736/55278277-0ada4100-52d8-11e9-9be5-379ce917a2c6.png)
