### ISSUE TITLE
Create brewmaster cards

### ISSUE THREAD

**Issue by GregStephen** [nss-evening-cohort-9/foundations-group-project-adios-pantalones#6]
# User Story
As a user, when I navigate to the brewmasters page, it loads cards with the brewmasters names, images of them, and a small description of them

# AC
**WHEN** the pages loads
**THEN** cards should populate with the brewmasters names, image and description

# Development
* Create brewmasters.html
* Link to main.css, main.js, bootstrap and fontawesome
* Add images to assets folder
* Create h1 tag "Brewmasters"
* Create div id="brewmastersDiv"
* Create a `printToDom` function - 2 inputs- divId, textToPrint
* Create `brewmasters` array full of 6 objects with keys - img, title, description
* Add a `brewMasterBuilder` function which has 2 inputs - `arrayOfBrewmasters`, `divID`
*`brewMasterBuilder` function should loop `arrayOfBrewmasters` and build up a domstring of bootstrap cards. It should then pass the string and the divId - `brewmastersDiv` to `printToDom` function

**Comment by zoeames** [comment]
👍

**Comment by wchipchase** [comment]
https://app.moqups.com/D3s3U7o2FC/edit/page/a222443f6

**Comment by wchipchase** [comment]
![image](https://user-images.githubusercontent.com/15699736/55278283-30674a80-52d8-11e9-9e89-395769f08709.png)
