### ISSUE TITLE
Create About Section

### ISSUE THREAD

**Issue by GregStephen** [nss-evening-cohort-9/foundations-group-project-adios-pantalones#8]
# User Story
As a user, when I navigate to the about page, I will see a few images with text about the brewery

# AC
**WHEN** I navigate to the About page
**THEN** I will see an image on the left with text to the right 
**AND** I will see below that an image on the right with text to the left

# Development
* Create the about.html
* Link to main.css, main.js, bootstrap and fontawesome
* Create a div with the id = "aboutDiv"
* Add images to the assets folder
* Create a div inside `aboutDiv` with the id="aboutFirstInfo"
* Create a div below that with the id="aboutSecondInfo"
* Add an image with id="aboutFirstImg" and text with id ="aboutFirstDescrip" to `aboutFirstInfo`
* Add an image with id="aboutSecondImg" and text with id ="aboutSecondDescrip" to `aboutSecondInfo`
* In css give `aboutFirstImg` a property of float: left, and `aboutSecondImg` float: right.
* Give all the text a property of text-align: justify and whatever further styling is necessary

**Comment by GregStephen** [comment]
floating and justify - https://stackoverflow.com/questions/15209389/wrapping-text-around-an-image-with-indentation-and-justify

**Comment by zoeames** [comment]
👍

**Comment by wchipchase** [comment]
https://app.moqups.com/D3s3U7o2FC/edit/page/ae1848f1d

**Comment by wchipchase** [comment]
![image](https://user-images.githubusercontent.com/15699736/55278299-81773e80-52d8-11e9-9837-9bbe0c609f44.png)
