### ISSUE TITLE
Create Comment Form

### ISSUE THREAD

**Issue by GregStephen** [nss-evening-cohort-9/foundations-group-project-adios-pantalones#9]
# User Story
As a user, when I fill out the form with my name and a comment it should print that info to the DOM.

# AC
**WHEN** the page loads there should be a form with a text comment input, an input for their name and a comment button
**AND** when I type in some stuff and hit the button
**THEN** the stuff should appear in the DOM (no formatting)
**AND** the input text should be cleared out

# Development
* Add form to the html, (two text inputs and a button)
* Add h2 tag in form "Tell us about us!"
* Add id on the comment button = `commentBtn`, add an eventListener that calls a function called `addComment`
* Add id on the name input = `nameInput` and id on the comment input = `commentInput`
* Make a div with an id = `comment-container`
* Make `addComment` function. Create a domString and have it concatenate the two input values.  Call `printToDom` and pass the domString and the divId = `comment-container`, clear out both of the input texts

**Comment by GregStephen** [comment]
bootstrap forms - https://getbootstrap.com/docs/4.3/components/forms/
sample form 
```html
<form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-group form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
```

**Comment by zoeames** [comment]
👍

**Comment by wchipchase** [comment]
https://app.moqups.com/D3s3U7o2FC/edit/page/ae1848f1d

**Comment by wchipchase** [comment]
![image](https://user-images.githubusercontent.com/15699736/55278300-86d48900-52d8-11e9-845c-ca5a4171c516.png)
